### ISSUE TITLE
Missing cache invalidation for development

### ISSUE THREAD

**Issue by enumag** [Kdyby/Validator#15]
Currently when I change some constraints annotations when programming in debug mode, Validator still uses the old constraints until I manually erase the cache. I dug into it a little and the reason is obvious - `Kdyby\Validator\Caching\Cache` doesn't add any dependencies to the cached data.

I'm not sure how to fix it though. One obvious solution would be to add another implementation of `Symfony\Component\Validator\Mapping\Cache\CacheInterface` which would never save anything and use that in debug mode.

Is this the right way to fix it or is there a better one? How does it work in Symfony?

By the way Kdyby/Doctrine suffers with the same problem - migrations never detect any changes until I erase cache.

**Comment by fprochazka** [comment]
Migrations are not handled by Kdyby, but generate proxies, validate, etc. should invalidate the cache on run.
https://github.com/Kdyby/DoctrineCache/blob/c31d0b5b89fe8fabfc6d8af03bdf38d1b712df1b/src/Kdyby/DoctrineCache/Cache.php#L92-L106

**Comment by enumag** [comment]
Well it doesn't but that's separate issue and off-topic here. I'll look into it later.

What are your thoughts for the Validator?

**Comment by enumag** [comment]
Closing in favor of #16.

**Comment by fprochazka** [comment]
It's not solved yet :) We can close it once the PR is accepted.

**Comment by enumag** [comment]
Fine. :-)

**Comment by fprochazka** [comment]
:+1:
