### ISSUE TITLE
Add Any constraint

### ISSUE THREAD

**Issue by enumag** [Kdyby/Validator#17]
Sometimes I'm thinking I might need to use a disjunction of symfony validator constraints. It was never completely necessary but I'm somehow nervous about the fact that there is no way to do that in symfony. Should we add such constraint to Kdyby?

Note for myself when I find time to implement it: Here is [some implementation](https://github.com/symfony/symfony/pull/11586) but it can't be used as is because it adds some methods to ExcecutionContext. It should be possible to implement it without creating subcontexts by removing the new violations from ConstraintViolationListInterface.

**Comment by enumag** [comment]
Maybe Condition constraint would not be bad either.

```
@Condition(if = <constraints>, then = <constraints>[, else = <constraints>])
```

**Comment by Majkl578** [comment]
Why don't you suggest this to Symfony itself?

**Comment by enumag** [comment]
Because it was closed there. https://github.com/symfony/symfony/pull/11586

**Comment by Majkl578** [comment]
Have you read the thread (and https://github.com/symfony/symfony/issues/5749) to find out the reasons? Maybe there is a reason why it's not in Symfony.

**Comment by enumag** [comment]
Yes, the only reason is that not many people complained.

**Comment by enumag** [comment]
@fprochazka What's your opinion about this?

**Comment by fprochazka** [comment]
I'm not against adding custom constraints :) As long as they are registered in a way where they can be overwritten with custom impl.

**Comment by enumag** [comment]
Improving expression constraint (symfony issue 11940) seems like better solution.
