### ISSUE TITLE
Add all validators as services

### ISSUE THREAD

**Issue by enumag** [Kdyby/Validator#19]
I don't like the usage of [this line](https://github.com/Kdyby/Validator/blob/debcd0f8633fcb03f3298560aaf4a934258659f6/src/Kdyby/Validator/ConstraintValidatorFactory.php#L54). Autowiring arguments at runtime seems ugly to me even though most of them don't have any.

I think we should add all constraint validators as services (with a new tag).

Optionally we might want to remove the runtime creation using DIC. What do you think?

**Comment by fprochazka** [comment]
@enumag I would make them not services, but service factories :)

**Comment by enumag** [comment]
@fprochazka Factories don't make any sense in this case IMO. You don't need more than one instance of each constraint validator.

**Comment by Majkl578** [comment]
Why?

**Comment by enumag** [comment]
@Majkl578 Why what? I already wrote the reasons.

**Comment by enumag** [comment]
Decided to not implement this.
